version: "3.9"

networks:
  algafood-network:
    driver: bridge

services:
  graapi-api:
    image: graapi-api
    command: ["java", "-jar", "api.jar"]
    environment:
      SPRING_PROFILES_ACTIVE: development
    networks:
      - graapi-network

  graapi-proxy:
    build: ./nginx
    image: graapi-proxy
    ports:
      - "80:80"
    networks:
      - graapi-network
    depends_on:
      - graapi-api
